export const FETCH_TASKS = "FETCH_TASKS";
export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";

export const FETCH_TASK_LISTS = "FETCH_TASK_LISTS";
export const CREATE_TASK_LIST = "CREATE_TASK_LIST";
export const DELETE_TASK_LIST = "DELETE_TASK_LIST";
export const UPDATE_TASK_LIST = "UPDATE_TASK_LIST";

